project_id = "iyuypkfksxfsutubcpay"

[functions.check-critical-orders]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = true

[functions.create-user]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.extract-certificate-data]
verify_jwt = true

[functions.extract-technician-data]
verify_jwt = true

[functions.demand-forecast]
verify_jwt = true

[functions.ai-proactive-check]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.search-reports]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false
