// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/supabase-client.ts
import { createClient } from "npm:@supabase/supabase-js@^2.80.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna informa\xE7\xF5es do usu\xE1rio Arrow atualmente autenticado (perfil e pap\xE9is).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "N\xE3o autenticado." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: roles }] = await Promise.all([
      supabase.from("profiles").select("id, full_name, email, company_id").eq("id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId)
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail(),
      profile,
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-service-orders.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^4";
var list_service_orders_default = defineTool2({
  name: "list_service_orders",
  title: "Listar Ordens de Servi\xE7o",
  description: "Lista as Ordens de Servi\xE7o (OS) do Arrow vis\xEDveis ao usu\xE1rio autenticado, respeitando permiss\xF5es (RLS). Retorna at\xE9 50 registros ordenados pelos mais recentes.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Quantidade m\xE1xima de OS a retornar (1-50). Padr\xE3o: 20."),
    status: z.string().optional().describe("Filtrar por status exato da OS (ex.: 'pending', 'completed').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "N\xE3o autenticado." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("service_orders").select("id, os_number, status, service_date, client_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: `Erro: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { orders: data }
    };
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z2 } from "npm:zod@^4";
var list_notifications_default = defineTool3({
  name: "list_notifications",
  title: "Listar Notifica\xE7\xF5es",
  description: "Lista as notifica\xE7\xF5es mais recentes do usu\xE1rio Arrow autenticado.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Quantidade m\xE1xima (1-50). Padr\xE3o: 20."),
    unread_only: z2.boolean().optional().describe("Se true, retorna apenas notifica\xE7\xF5es n\xE3o lidas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, unread_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "N\xE3o autenticado." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("notifications").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (unread_only) query = query.eq("read", false);
    const { data, error } = await query;
    if (error) {
      return {
        content: [{ type: "text", text: `Erro: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { notifications: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iyuypkfksxfsutubcpay";
var mcp_default = defineMcp({
  name: "arrow-mcp",
  title: "Arrow MCP",
  version: "0.1.0",
  instructions: "Ferramentas do Arrow (gest\xE3o de OS, t\xE9cnicos, qualidade). Todas as chamadas usam o usu\xE1rio autenticado via OAuth e respeitam RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_service_orders_default, list_notifications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
