/*
# Checklists and technician scheduling

1. New Tables
- Checklist templates, checklist items, checklist responses, and item responses.
- Technician reservations, absences, on-call schedules, home-office schedules, and company holidays.

2. Security
- RLS enabled and four separate company-scoped CRUD policies are applied to every table.
*/
CREATE TABLE IF NOT EXISTS checklist_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, name text NOT NULL, description text, task_type_id uuid REFERENCES task_types(id) ON DELETE SET NULL, is_mandatory boolean DEFAULT false, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS checklist_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, template_id uuid NOT NULL REFERENCES checklist_templates(id) ON DELETE CASCADE, item_order int DEFAULT 0, description text NOT NULL, item_type text DEFAULT 'boolean', is_required boolean DEFAULT false);
CREATE TABLE IF NOT EXISTS checklist_responses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, task_id uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE, template_id uuid REFERENCES checklist_templates(id) ON DELETE SET NULL, technician_id uuid REFERENCES technicians(id) ON DELETE SET NULL, completed_at timestamptz, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS checklist_item_responses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, response_id uuid NOT NULL REFERENCES checklist_responses(id) ON DELETE CASCADE, item_id uuid NOT NULL REFERENCES checklist_items(id) ON DELETE CASCADE, value_boolean boolean, value_text text, value_number numeric, value_photo_path text, answered_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS technician_reservations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, technician_id uuid REFERENCES technicians(id) ON DELETE CASCADE, reserved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, start_date date NOT NULL, end_date date NOT NULL, start_time time, end_time time, client_id uuid REFERENCES clients(id) ON DELETE SET NULL, vessel_id uuid REFERENCES vessels(id) ON DELETE SET NULL, service_order_id uuid REFERENCES service_orders(id) ON DELETE SET NULL, status text DEFAULT 'reserved', reason text, includes_travel boolean DEFAULT false, includes_overnight boolean DEFAULT false, notes text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS technician_absences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, technician_id uuid REFERENCES technicians(id) ON DELETE CASCADE, absence_type text, start_date date NOT NULL, end_date date NOT NULL, start_time time, end_time time, reason text, status text DEFAULT 'pending', approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, approved_at timestamptz, notes text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, attachment_url text, attachment_name text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS technician_on_call (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, technician_id uuid REFERENCES technicians(id) ON DELETE CASCADE, on_call_date date NOT NULL, start_time time, end_time time, is_holiday boolean DEFAULT false, is_weekend boolean DEFAULT false, notes text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS home_office_schedules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, technician_id uuid REFERENCES technicians(id) ON DELETE CASCADE, start_date date NOT NULL, end_date date NOT NULL, notes text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS company_holidays (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, holiday_date date NOT NULL, name text NOT NULL, is_recurring boolean DEFAULT false, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['checklist_templates','checklist_items','checklist_responses','checklist_item_responses','technician_reservations','technician_absences','technician_on_call','home_office_schedules','company_holidays'] LOOP
EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO authenticated',t);
EXECUTE format('DROP POLICY IF EXISTS "select_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "select_%s" ON %I FOR SELECT TO authenticated USING (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
EXECUTE format('DROP POLICY IF EXISTS "insert_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "insert_%s" ON %I FOR INSERT TO authenticated WITH CHECK (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
EXECUTE format('DROP POLICY IF EXISTS "update_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "update_%s" ON %I FOR UPDATE TO authenticated USING (company_id = get_user_company_id() OR company_id IS NULL) WITH CHECK (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
EXECUTE format('DROP POLICY IF EXISTS "delete_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "delete_%s" ON %I FOR DELETE TO authenticated USING (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
END LOOP; END $$;
CREATE INDEX IF NOT EXISTS idx_reservations_technician_dates ON technician_reservations(technician_id,start_date,end_date);
CREATE INDEX IF NOT EXISTS idx_absences_technician_dates ON technician_absences(technician_id,start_date,end_date);