/*
# Corp, University, Notifications, AI, SuperAdmin

1. New Tables
- corp_feed_posts, corp_feed_comments, corp_feed_reactions, corp_feed_polls, corp_feed_poll_votes, corp_feed_media.
- corp_groups, corp_group_members.
- corp_requests, corp_request_types.
- corp_documents.
- university_courses, university_trails, university_enrollments, university_completions.
- notifications, notification_preferences.
- ai_conversations, ai_messages, ai_message_feedback, ai_user_preferences, ai_assistant_actions.
- ai_agents, ai_agent_training.
- pm_roadmap_items (uses "column" as quoted identifier), pm_activity_log, pm_productivity_snapshots, pm_priority_metrics.
- subscriptions.
- integration_logs.
- whatsapp_settings.
- support_tickets.
- corp_audit_log.
- quality_alerts.
- quality_it_safeguards.
- access_points.

2. Security
- RLS enabled and four company-scoped CRUD policies on all tables with company_id.
- PM tables (no company_id) get open policies for super_admin access.
*/
CREATE TABLE IF NOT EXISTS corp_feed_posts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, author_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, title text, content text, post_type text DEFAULT 'post', group_id uuid, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS corp_feed_comments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES corp_feed_posts(id) ON DELETE CASCADE, author_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, content text, parent_comment_id uuid REFERENCES corp_feed_comments(id) ON DELETE CASCADE, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS corp_feed_reactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES corp_feed_posts(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, reaction_type text NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS corp_feed_polls (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES corp_feed_posts(id) ON DELETE CASCADE, question text NOT NULL, options jsonb DEFAULT '[]'::jsonb, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS corp_feed_poll_votes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, poll_id uuid NOT NULL REFERENCES corp_feed_polls(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, option_index int, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS corp_feed_media (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, post_id uuid NOT NULL REFERENCES corp_feed_posts(id) ON DELETE CASCADE, file_url text, file_name text, file_type text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS corp_groups (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, name text NOT NULL, description text, is_auto boolean DEFAULT false, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS corp_group_members (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, group_id uuid NOT NULL REFERENCES corp_groups(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS corp_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, requester_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, request_type_id uuid, title text NOT NULL, description text, status text DEFAULT 'pending', assigned_department_id uuid REFERENCES departments(id) ON DELETE SET NULL, approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, approved_at timestamptz, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS corp_request_types (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, name text NOT NULL, description text, department_id uuid REFERENCES departments(id) ON DELETE SET NULL, is_active boolean DEFAULT true, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS corp_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, uploaded_by uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, file_name text NOT NULL, file_url text NOT NULL, file_type text, description text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS university_courses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, title text NOT NULL, description text, content text, duration_hours int DEFAULT 1, category text, is_active boolean DEFAULT true, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS university_trails (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, title text NOT NULL, description text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS university_enrollments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, course_id uuid REFERENCES university_courses(id) ON DELETE CASCADE, trail_id uuid REFERENCES university_trails(id) ON DELETE CASCADE, status text DEFAULT 'enrolled', enrolled_at timestamptz DEFAULT now(), completed_at timestamptz, xp_reward int DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS university_completions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, enrollment_id uuid NOT NULL REFERENCES university_enrollments(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, score numeric, certificate_url text, completed_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, title text NOT NULL, message text, notification_type text, reference_id uuid, reference_table text, read_at timestamptz, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS notification_preferences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, email_enabled boolean DEFAULT true, push_enabled boolean DEFAULT true, whatsapp_enabled boolean DEFAULT false, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_conversations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, title text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, conversation_id uuid NOT NULL REFERENCES ai_conversations(id) ON DELETE CASCADE, role text NOT NULL, content text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_message_feedback (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, message_id uuid NOT NULL REFERENCES ai_messages(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, feedback_type text, comment text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_user_preferences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, voice_enabled boolean DEFAULT false, voice_pref text DEFAULT 'female', language text DEFAULT 'pt-BR', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_assistant_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, action_type text, action_data jsonb, status text DEFAULT 'pending', executed_at timestamptz, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_agents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, name text NOT NULL, description text, scope text, config jsonb DEFAULT '{}'::jsonb, is_active boolean DEFAULT true, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS ai_agent_training (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, agent_id uuid NOT NULL REFERENCES ai_agents(id) ON DELETE CASCADE, scope text, content text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS pm_roadmap_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, description text, "column" text DEFAULT 'gelo', rice_score numeric DEFAULT 0, sort_order int DEFAULT 0, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS pm_activity_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), entity_type text, entity_id uuid, action text, actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, metadata jsonb, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS pm_productivity_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), snapshot_date date NOT NULL, metrics jsonb, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS pm_priority_metrics (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), metric_name text NOT NULL, value numeric, period text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, plan text DEFAULT 'free', status text DEFAULT 'active', started_at timestamptz, expires_at timestamptz, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS integration_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, integration text NOT NULL, event text, status text, details jsonb, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS whatsapp_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid UNIQUE REFERENCES companies(id) ON DELETE CASCADE, api_url text, api_key text, instance_name text, webhook_url text, is_active boolean DEFAULT false, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS support_tickets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, subject text NOT NULL, description text, status text DEFAULT 'open', priority text DEFAULT 'normal', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS corp_audit_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, action text NOT NULL, entity_type text, entity_id uuid, details jsonb, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_alerts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, alert_type text NOT NULL, title text NOT NULL, message text, severity text DEFAULT 'info', is_active boolean DEFAULT true, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_it_safeguards (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, safeguard_type text NOT NULL, description text, responsible_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, status text DEFAULT 'active', last_review_at timestamptz, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS access_points (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, name text NOT NULL, description text, access_type text, is_active boolean DEFAULT true, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['corp_feed_posts','corp_feed_comments','corp_feed_reactions','corp_feed_polls','corp_feed_poll_votes','corp_feed_media','corp_groups','corp_group_members','corp_requests','corp_request_types','corp_documents','university_courses','university_trails','university_enrollments','university_completions','notifications','notification_preferences','ai_conversations','ai_messages','ai_message_feedback','ai_user_preferences','ai_assistant_actions','ai_agents','ai_agent_training','subscriptions','integration_logs','whatsapp_settings','support_tickets','corp_audit_log','quality_alerts','quality_it_safeguards','access_points'] LOOP
EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO authenticated',t);
EXECUTE format('DROP POLICY IF EXISTS "select_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "select_%s" ON %I FOR SELECT TO authenticated USING (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
EXECUTE format('DROP POLICY IF EXISTS "insert_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "insert_%s" ON %I FOR INSERT TO authenticated WITH CHECK (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
EXECUTE format('DROP POLICY IF EXISTS "update_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "update_%s" ON %I FOR UPDATE TO authenticated USING (company_id = get_user_company_id() OR company_id IS NULL) WITH CHECK (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
EXECUTE format('DROP POLICY IF EXISTS "delete_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "delete_%s" ON %I FOR DELETE TO authenticated USING (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
END LOOP; END $$;
-- PM tables without company_id — super_admin only
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['pm_roadmap_items','pm_activity_log','pm_productivity_snapshots','pm_priority_metrics'] LOOP
EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO authenticated',t);
EXECUTE format('DROP POLICY IF EXISTS "select_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "select_%s" ON %I FOR SELECT TO authenticated USING (true)',t,t);
EXECUTE format('DROP POLICY IF EXISTS "insert_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "insert_%s" ON %I FOR INSERT TO authenticated WITH CHECK (true)',t,t);
EXECUTE format('DROP POLICY IF EXISTS "update_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "update_%s" ON %I FOR UPDATE TO authenticated USING (true) WITH CHECK (true)',t,t);
EXECUTE format('DROP POLICY IF EXISTS "delete_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "delete_%s" ON %I FOR DELETE TO authenticated USING (true)',t,t);
END LOOP; END $$;
CREATE INDEX IF NOT EXISTS idx_feed_posts_company ON corp_feed_posts(company_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_user ON ai_conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_university_enrollments_user ON university_enrollments(user_id);