/*
# CRM and measurement foundations

1. New Tables
- CRM products, stock, buyers, opportunities, activities, sales, and sale items.
- Client contacts, addresses, and legal entities.
- Measurement headers and labor, material, service, travel, and expense lines.
- Measurement settings, service rates, and city distances.

2. Security
- All tables enable RLS with four company-scoped CRUD policies for authenticated users.
*/

CREATE TABLE IF NOT EXISTS client_contacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, client_id uuid NOT NULL REFERENCES clients(id) ON DELETE CASCADE, name text NOT NULL, role text, email text, phone text, whatsapp text, is_primary boolean DEFAULT false, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS client_addresses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, client_id uuid NOT NULL REFERENCES clients(id) ON DELETE CASCADE, label text, cep text, street text, street_number text, city text, state text, complement text, is_primary boolean DEFAULT false, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS client_legal_entities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, client_id uuid NOT NULL REFERENCES clients(id) ON DELETE CASCADE, legal_name text, cnpj text, is_primary boolean DEFAULT false, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS crm_products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, name text NOT NULL, description text, category text, unit_value numeric DEFAULT 0, active boolean DEFAULT true, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS stock_products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, name text NOT NULL, sku text, current_quantity numeric DEFAULT 0, unit_value numeric DEFAULT 0, min_quantity numeric DEFAULT 0, active boolean DEFAULT true, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS crm_buyers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, client_id uuid REFERENCES clients(id) ON DELETE SET NULL, name text NOT NULL, email text, phone text, role text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS crm_opportunities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, client_id uuid REFERENCES clients(id) ON DELETE SET NULL, buyer_id uuid REFERENCES crm_buyers(id) ON DELETE SET NULL, title text NOT NULL, description text, stage text DEFAULT 'lead', status text DEFAULT 'open', value numeric DEFAULT 0, assigned_to uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS crm_opportunity_activities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, opportunity_id uuid NOT NULL REFERENCES crm_opportunities(id) ON DELETE CASCADE, user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, activity_type text, description text, activity_date timestamptz DEFAULT now(), created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS crm_sales (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, opportunity_id uuid REFERENCES crm_opportunities(id) ON DELETE SET NULL, client_id uuid REFERENCES clients(id) ON DELETE SET NULL, sale_number text, total_amount numeric DEFAULT 0, notes text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, status text DEFAULT 'draft', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS crm_sale_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, sale_id uuid NOT NULL REFERENCES crm_sales(id) ON DELETE CASCADE, stock_product_id uuid REFERENCES stock_products(id) ON DELETE SET NULL, name text NOT NULL, quantity numeric DEFAULT 1, unit_value numeric DEFAULT 0, markup_percentage numeric DEFAULT 0, total_value numeric DEFAULT 0, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS measurements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, service_order_id uuid NOT NULL REFERENCES service_orders(id) ON DELETE CASCADE, category text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, status text DEFAULT 'draft', finalized_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, finalized_at timestamptz, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS measurement_man_hours (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, measurement_id uuid NOT NULL REFERENCES measurements(id) ON DELETE CASCADE, entry_date date, start_time time, end_time time, hour_type text, work_type text, technician_id uuid REFERENCES technicians(id) ON DELETE SET NULL, technician_name text, technician_role text, total_hours numeric DEFAULT 0, hourly_rate numeric DEFAULT 0, total_value numeric DEFAULT 0);
CREATE TABLE IF NOT EXISTS measurement_materials (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, measurement_id uuid NOT NULL REFERENCES measurements(id) ON DELETE CASCADE, name text NOT NULL, quantity numeric DEFAULT 1, unit_value numeric DEFAULT 0, markup_percentage numeric DEFAULT 0, total_value numeric DEFAULT 0, external_product_id text, external_product_code text, source text);
CREATE TABLE IF NOT EXISTS measurement_services (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, measurement_id uuid NOT NULL REFERENCES measurements(id) ON DELETE CASCADE, name text NOT NULL, value numeric DEFAULT 0, description text);
CREATE TABLE IF NOT EXISTS measurement_travels (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, measurement_id uuid NOT NULL REFERENCES measurements(id) ON DELETE CASCADE, travel_type text, from_city text, to_city text, distance_km numeric DEFAULT 0, km_rate numeric DEFAULT 0, fixed_value numeric DEFAULT 0, total_value numeric DEFAULT 0, description text);
CREATE TABLE IF NOT EXISTS measurement_expenses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, measurement_id uuid NOT NULL REFERENCES measurements(id) ON DELETE CASCADE, expense_type text, base_value numeric DEFAULT 0, admin_fee_percentage numeric DEFAULT 0, admin_fee_amount numeric DEFAULT 0, total_value numeric DEFAULT 0, description text);
CREATE TABLE IF NOT EXISTS measurement_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid UNIQUE REFERENCES companies(id) ON DELETE CASCADE, km_rate numeric DEFAULT 0, default_material_markup numeric DEFAULT 0, expense_admin_fee numeric DEFAULT 0, tax_cativo numeric DEFAULT 0, tax_laboratorio numeric DEFAULT 0, tax_externo numeric DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS service_rates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, role_type text, hour_type text, work_type text, rate_value numeric DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS city_distances (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, from_city text NOT NULL, to_city text NOT NULL, distance_km numeric DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['client_contacts','client_addresses','client_legal_entities','crm_products','stock_products','crm_buyers','crm_opportunities','crm_opportunity_activities','crm_sales','crm_sale_items','measurements','measurement_man_hours','measurement_materials','measurement_services','measurement_travels','measurement_expenses','measurement_settings','service_rates','city_distances'] LOOP
  EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO authenticated',t,t);
  EXECUTE format('DROP POLICY IF EXISTS "select_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "select_%s" ON %I FOR SELECT TO authenticated USING (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
  EXECUTE format('DROP POLICY IF EXISTS "insert_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "insert_%s" ON %I FOR INSERT TO authenticated WITH CHECK (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
  EXECUTE format('DROP POLICY IF EXISTS "update_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "update_%s" ON %I FOR UPDATE TO authenticated USING (company_id = get_user_company_id() OR company_id IS NULL) WITH CHECK (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
  EXECUTE format('DROP POLICY IF EXISTS "delete_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "delete_%s" ON %I FOR DELETE TO authenticated USING (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
END LOOP; END $$;

CREATE OR REPLACE FUNCTION decrement_stock_quantity(p_product_id uuid, p_quantity numeric) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ BEGIN UPDATE stock_products SET current_quantity = current_quantity - p_quantity WHERE id = p_product_id AND current_quantity >= p_quantity; END $$;
GRANT EXECUTE ON FUNCTION decrement_stock_quantity(uuid,numeric) TO authenticated;
CREATE INDEX IF NOT EXISTS idx_measurements_order ON measurements(service_order_id);
CREATE INDEX IF NOT EXISTS idx_opportunities_company_stage ON crm_opportunities(company_id, stage);