/*
# Quality Suppliers, Context, Planning, Risks, Devices, Communication, Knowledge, Processes

1. New Tables
- quality_suppliers + evaluation/criteria/incidents/documents.
- quality_interested_parties + evidences + party_processes.
- quality_competitors + analyses + analysis_items.
- quality_terms, quality_org_context, quality_org_chart_nodes, quality_context_items, quality_context_versions.
- quality_processes + sipoc + activities + process_documents + process_document_history.
- quality_risks, quality_risk_events, quality_risk_actions.
- quality_objectives, quality_indicators, quality_indicator_measurements, quality_planned_changes.
- quality_objective_risks, quality_objective_parties (junction tables — no company_id column, manual policies).
- quality_measuring_devices, quality_calibrations, quality_calibration_checkpoints.
- quality_communication_plan, quality_communication_log.
- quality_knowledge_articles.

2. Security
- RLS enabled on all tables. Company-scoped CRUD policies applied to all tables with company_id.
- Junction tables (quality_objective_risks, quality_objective_parties) get manual policies scoping through parent tables.
*/
CREATE TABLE IF NOT EXISTS quality_suppliers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, name text NOT NULL, tax_id text, category text, criticality text DEFAULT 'medium', status text DEFAULT 'active', contact_name text, contact_email text, contact_phone text, scope_description text, notes text, requalification_frequency_months int DEFAULT 12, last_evaluation_at timestamptz, next_evaluation_due date, current_score numeric, current_grade text, owner_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_supplier_evaluations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, supplier_id uuid NOT NULL REFERENCES quality_suppliers(id) ON DELETE CASCADE, kind text, evaluation_date date, period_start date, period_end date, score numeric, grade text, status_after text, evaluator_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, summary text, recommendations text, next_due_at date, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_supplier_evaluation_criteria (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, evaluation_id uuid NOT NULL REFERENCES quality_supplier_evaluations(id) ON DELETE CASCADE, criterion_code text, weight numeric DEFAULT 1, score numeric, notes text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_supplier_incidents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, supplier_id uuid NOT NULL REFERENCES quality_suppliers(id) ON DELETE CASCADE, incident_date date, severity text, description text, linked_ncr_id uuid REFERENCES quality_ncrs(id) ON DELETE SET NULL, resolved_at timestamptz, resolved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, reported_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_supplier_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, supplier_id uuid NOT NULL REFERENCES quality_suppliers(id) ON DELETE CASCADE, document_type text, file_url text, file_name text, valid_until date, uploaded_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_interested_parties (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, name text NOT NULL, category text, needs_expectations text, monitoring_method text, relevance text, owner_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, status text DEFAULT 'active', review_frequency_months int DEFAULT 12, last_reviewed_at timestamptz, last_reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, last_review_notes text, next_review_due_at date, power_level int DEFAULT 2, interest_level int DEFAULT 2, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_interested_party_evidences (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, party_id uuid NOT NULL REFERENCES quality_interested_parties(id) ON DELETE CASCADE, title text, description text, evidence_type text, document_id uuid, external_file_path text, evidence_date date, valid_until date, uploaded_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_interested_party_processes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, party_id uuid NOT NULL REFERENCES quality_interested_parties(id) ON DELETE CASCADE, process_id uuid, relevance text, relationship_type text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_competitors (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, name text NOT NULL, market_segment text, size_category text, positioning text, estimated_market_share numeric, price_range text, strengths text, weaknesses text, notes text, website text, interested_party_id uuid REFERENCES quality_interested_parties(id) ON DELETE SET NULL, is_active boolean DEFAULT true, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_competitor_analyses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, title text NOT NULL, analysis_period text, summary text, methodology text, conclusions text, author_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, performed_at timestamptz DEFAULT now(), next_review_at date, status text DEFAULT 'draft', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_competitor_analysis_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, analysis_id uuid NOT NULL REFERENCES quality_competitor_analyses(id) ON DELETE CASCADE, competitor_id uuid REFERENCES quality_competitors(id) ON DELETE SET NULL, dimension text, our_position text, competitor_position text, gap_type text, gap_description text, recommended_action text, linked_risk_id uuid, linked_context_item_id uuid, sort_order int DEFAULT 0, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_terms (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, term text NOT NULL, definition text NOT NULL, source_norm_id uuid REFERENCES quality_reference_norms(id) ON DELETE SET NULL, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_org_context (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, internal_issues text, external_issues text, applicable_scope text, review_frequency_months int DEFAULT 12, last_reviewed_at timestamptz, last_reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, last_review_notes text, next_review_due_at date, excluded_clauses text, mission text, vision text, values text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_org_chart_nodes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, parent_id uuid REFERENCES quality_org_chart_nodes(id) ON DELETE SET NULL, title text NOT NULL, user_id uuid REFERENCES profiles(id) ON DELETE SET NULL, department_id uuid REFERENCES departments(id) ON DELETE SET NULL, responsibilities text, authority text, order_index int DEFAULT 0, active boolean DEFAULT true, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_context_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, category text, title text NOT NULL, description text, impact_level text, position text, linked_risk_id uuid, department_id uuid REFERENCES departments(id) ON DELETE SET NULL, analysis_period text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_context_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, version_number int DEFAULT 1, scope text, internal_issues text, external_issues text, items_snapshot jsonb, reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, reviewed_at timestamptz, review_notes text, approved boolean DEFAULT false, approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, approved_at timestamptz, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_processes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, name text NOT NULL, type text, description text, status text DEFAULT 'active', owner_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, current_document_id uuid, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_process_sipoc (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, process_id uuid NOT NULL REFERENCES quality_processes(id) ON DELETE CASCADE, suppliers text, inputs text, activities text, outputs text, customers text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_process_activities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, process_id uuid NOT NULL REFERENCES quality_processes(id) ON DELETE CASCADE, order_index int DEFAULT 0, activity text, responsible_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, indicators text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_process_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, process_id uuid NOT NULL REFERENCES quality_processes(id) ON DELETE CASCADE, document_id uuid NOT NULL REFERENCES quality_documents(id) ON DELETE CASCADE, relationship_type text, notes text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_process_document_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, process_id uuid NOT NULL REFERENCES quality_processes(id) ON DELETE CASCADE, previous_document_id uuid REFERENCES quality_documents(id) ON DELETE SET NULL, new_document_id uuid REFERENCES quality_documents(id) ON DELETE SET NULL, changed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, reason text, changed_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_risks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, code text, kind text, title text NOT NULL, description text, source text, source_ref_id uuid, category text, owner_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, probability int DEFAULT 1, impact int DEFAULT 1, score int DEFAULT 1, severity text DEFAULT 'low', residual_probability int, residual_impact int, residual_score int, residual_severity text, treatment text, treatment_plan text, treatment_due_date date, status text DEFAULT 'open', status_changed_at timestamptz, review_frequency_months int DEFAULT 12, last_reviewed_at timestamptz, next_review_due_at date, reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, closed_at timestamptz, closure_notes text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_risk_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, risk_id uuid NOT NULL REFERENCES quality_risks(id) ON DELETE CASCADE, at timestamptz DEFAULT now(), description text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_risk_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, risk_id uuid NOT NULL REFERENCES quality_risks(id) ON DELETE CASCADE, description text, responsible_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, due_date date, status text DEFAULT 'open', completed_at timestamptz, evidence_url text, notes text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_objectives (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, code text, title text NOT NULL, description text, owner_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, policy_version_id uuid REFERENCES quality_policy_versions(id) ON DELETE SET NULL, period_start date, period_end date, status text DEFAULT 'active', target_value numeric, unit text, notes text, objective_scope text, time_horizon text, linked_to text, parent_objective_id uuid REFERENCES quality_objectives(id) ON DELETE SET NULL, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_indicators (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, objective_id uuid REFERENCES quality_objectives(id) ON DELETE SET NULL, code text, name text NOT NULL, unit text, target_value numeric, formula text, frequency text, responsible_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, status text DEFAULT 'active', notes text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_indicator_measurements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, indicator_id uuid NOT NULL REFERENCES quality_indicators(id) ON DELETE CASCADE, period_label text, period_start date, period_end date, value numeric, note text, measured_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_planned_changes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, code text, title text NOT NULL, description text, change_type text, justification text, impact_assessment text, planned_for date, status text DEFAULT 'proposed', requested_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, approved_at timestamptz, implemented_at timestamptz, linked_risk_ids uuid[], notes text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_objective_risks (objective_id uuid NOT NULL REFERENCES quality_objectives(id) ON DELETE CASCADE, risk_id uuid NOT NULL REFERENCES quality_risks(id) ON DELETE CASCADE, PRIMARY KEY (objective_id, risk_id));
CREATE TABLE IF NOT EXISTS quality_objective_parties (objective_id uuid NOT NULL REFERENCES quality_objectives(id) ON DELETE CASCADE, party_id uuid NOT NULL REFERENCES quality_interested_parties(id) ON DELETE CASCADE, PRIMARY KEY (objective_id, party_id));
CREATE TABLE IF NOT EXISTS quality_measuring_devices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, code text, name text NOT NULL, description text, manufacturer text, model text, serial_number text, measurement_range text, unit text, resolution text, accuracy text, location text, responsible_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, status text DEFAULT 'active', criticality text DEFAULT 'medium', calibration_frequency_months int DEFAULT 12, last_calibration_at timestamptz, next_calibration_due date, acquired_at date, retired_at timestamptz, notes text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_calibrations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, device_id uuid NOT NULL REFERENCES quality_measuring_devices(id) ON DELETE CASCADE, kind text, calibration_date date, result text, provider_supplier_id uuid REFERENCES quality_suppliers(id) ON DELETE SET NULL, certificate_number text, certificate_file_url text, certificate_file_name text, cost numeric, measurement_uncertainty text, traceability text, valid_until date, restrictions text, next_due_at date, performed_by_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, notes text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_calibration_checkpoints (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, calibration_id uuid NOT NULL REFERENCES quality_calibrations(id) ON DELETE CASCADE, nominal_value numeric, measured_value numeric, error numeric, tolerance numeric, pass boolean, notes text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_communication_plan (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, subject text NOT NULL, communication_type text, target_audience text, channel text, frequency text, owner_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, next_scheduled_at timestamptz, status text DEFAULT 'active', notes text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_communication_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, plan_id uuid REFERENCES quality_communication_plan(id) ON DELETE SET NULL, executed_at timestamptz DEFAULT now(), executed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, evidence_url text, notes text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS quality_knowledge_articles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid REFERENCES companies(id) ON DELETE CASCADE, title text NOT NULL, body text, category text, tags text[], source_type text, source_id uuid, author_id uuid REFERENCES auth.users(id) ON DELETE SET NULL, status text DEFAULT 'draft', version int DEFAULT 1, published_at timestamptz, review_period_months int DEFAULT 12, reviewed_at timestamptz, reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, review_due_at date, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());

-- Apply RLS + policies to all tables WITH company_id
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['quality_suppliers','quality_supplier_evaluations','quality_supplier_evaluation_criteria','quality_supplier_incidents','quality_supplier_documents','quality_interested_parties','quality_interested_party_evidences','quality_interested_party_processes','quality_competitors','quality_competitor_analyses','quality_competitor_analysis_items','quality_terms','quality_org_context','quality_org_chart_nodes','quality_context_items','quality_context_versions','quality_processes','quality_process_sipoc','quality_process_activities','quality_process_documents','quality_process_document_history','quality_risks','quality_risk_events','quality_risk_actions','quality_objectives','quality_indicators','quality_indicator_measurements','quality_planned_changes','quality_measuring_devices','quality_calibrations','quality_calibration_checkpoints','quality_communication_plan','quality_communication_log','quality_knowledge_articles'] LOOP
EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO authenticated',t);
EXECUTE format('DROP POLICY IF EXISTS "select_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "select_%s" ON %I FOR SELECT TO authenticated USING (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
EXECUTE format('DROP POLICY IF EXISTS "insert_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "insert_%s" ON %I FOR INSERT TO authenticated WITH CHECK (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
EXECUTE format('DROP POLICY IF EXISTS "update_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "update_%s" ON %I FOR UPDATE TO authenticated USING (company_id = get_user_company_id() OR company_id IS NULL) WITH CHECK (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
EXECUTE format('DROP POLICY IF EXISTS "delete_%s" ON %I',t,t); EXECUTE format('CREATE POLICY "delete_%s" ON %I FOR DELETE TO authenticated USING (company_id = get_user_company_id() OR company_id IS NULL)',t,t);
END LOOP; END $$;

-- Junction tables: manual policies (no company_id column — scope through parent ownership)
ALTER TABLE quality_objective_risks ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON quality_objective_risks TO authenticated;
DROP POLICY IF EXISTS "select_obj_risks" ON quality_objective_risks;
CREATE POLICY "select_obj_risks" ON quality_objective_risks FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM quality_objectives WHERE quality_objectives.id = objective_id AND (quality_objectives.company_id = get_user_company_id() OR quality_objectives.company_id IS NULL)));
DROP POLICY IF EXISTS "insert_obj_risks" ON quality_objective_risks;
CREATE POLICY "insert_obj_risks" ON quality_objective_risks FOR INSERT TO authenticated WITH CHECK (EXISTS(SELECT 1 FROM quality_objectives WHERE quality_objectives.id = objective_id AND (quality_objectives.company_id = get_user_company_id() OR quality_objectives.company_id IS NULL)));
DROP POLICY IF EXISTS "delete_obj_risks" ON quality_objective_risks;
CREATE POLICY "delete_obj_risks" ON quality_objective_risks FOR DELETE TO authenticated USING (EXISTS(SELECT 1 FROM quality_objectives WHERE quality_objectives.id = objective_id AND (quality_objectives.company_id = get_user_company_id() OR quality_objectives.company_id IS NULL)));

ALTER TABLE quality_objective_parties ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON quality_objective_parties TO authenticated;
DROP POLICY IF EXISTS "select_obj_parties" ON quality_objective_parties;
CREATE POLICY "select_obj_parties" ON quality_objective_parties FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM quality_objectives WHERE quality_objectives.id = objective_id AND (quality_objectives.company_id = get_user_company_id() OR quality_objectives.company_id IS NULL)));
DROP POLICY IF EXISTS "insert_obj_parties" ON quality_objective_parties;
CREATE POLICY "insert_obj_parties" ON quality_objective_parties FOR INSERT TO authenticated WITH CHECK (EXISTS(SELECT 1 FROM quality_objectives WHERE quality_objectives.id = objective_id AND (quality_objectives.company_id = get_user_company_id() OR quality_objectives.company_id IS NULL)));
DROP POLICY IF EXISTS "delete_obj_parties" ON quality_objective_parties;
CREATE POLICY "delete_obj_parties" ON quality_objective_parties FOR DELETE TO authenticated USING (EXISTS(SELECT 1 FROM quality_objectives WHERE quality_objectives.id = objective_id AND (quality_objectives.company_id = get_user_company_id() OR quality_objectives.company_id IS NULL)));

CREATE INDEX IF NOT EXISTS idx_suppliers_company ON quality_suppliers(company_id);
CREATE INDEX IF NOT EXISTS idx_risks_company ON quality_risks(company_id);
CREATE INDEX IF NOT EXISTS idx_devices_company ON quality_measuring_devices(company_id);
CREATE INDEX IF NOT EXISTS idx_processes_company ON quality_processes(company_id);